### ISSUE TITLE
Bug: A lot of implicit conversion -> loss of precision

### ISSUE THREAD

**Issue by madskjeldgaard** [tremblap/IBufWr#1]
Hi! 

Thanks for this great plugin, I just want to let you know that there is a lot of implicit conversion happening in this plugin code that may lead to loss in precision. Specifically, a lot of implicit conversions between double and float (bufData is a float array and filled with calculations based on a mix of floats and doubles that will implicitly convert to floats and lose precision). The same goes for implicit conversions between 64 and 32 bit integers. This all becomes clear if you activate warnings as errors in the compiler when compiling it :)

**Comment by tremblap** [comment]
thanks @madskjeldgaard - I'll look at this but I thought I had been careful that my internal processes were in 64-bit and I converted just at writing stage, but I'll check the code thanks.

**Comment by tremblap** [comment]
do I understand well that the auto casting in your refactor in #3 will actually sort this too? If not, I'll get sorting it

**Comment by madskjeldgaard** [comment]
I think a lot of it is fixed yeah so feel free to close :)
Best regards,
Mads Kjeldgaard

🐬 *website*: madskjeldgaard.dk
🐒 *music label*: exformal.art
🐸 *creative tech*: hyaline.systems



Den fre. 22. nov. 2024 kl. 15.03 skrev tremblap ***@***.***>:

**Comment by tremblap** [comment]
@madskjeldgaard I am trying to activate you wise suggestion:

>> This all becomes clear if you activate warnings as errors in the compiler when compiling it

but I cannot make this happen... help?

**Comment by tremblap** [comment]
-Wall -Wextra do not yield any error...
